#!/usr/bin/env python3
"""
===========================================================
AI-Powered Enterprise SBOM & CBOM Report Generator
===========================================================

Author  : Premchand
Version : 1.0.0

Description:
------------
Reads CycloneDX SBOM and CBOM JSON files, sends them to
Claude for analysis, and generates enterprise-grade
security and compliance reports.

Future Outputs
--------------
- Markdown Report
- HTML Report
- PDF Report
- GitHub Step Summary

"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
from pathlib import Path
from datetime import datetime

import anthropic
# ==========================================================
# Configuration
# ==========================================================

CLAUDE_MODEL = "claude-sonnet-4-20250514"

MAX_TOKENS = 12000

TEMPERATURE = 0

API_KEY_ENV = "CLAUDE_API_KEY"

LOG_LEVEL = logging.INFO
# ==========================================================
# Logging
# ==========================================================

logging.basicConfig(
    level=LOG_LEVEL,
    format="%(asctime)s | %(levelname)-8s | %(message)s",
)

logger = logging.getLogger("report-generator")
# ==========================================================
# CLI
# ==========================================================

def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Enterprise SBOM & CBOM Report Generator"
    )

    parser.add_argument(
        "--sbom",
        required=True,
        help="Path to SBOM JSON",
    )

    parser.add_argument(
        "--cbom",
        required=True,
        help="Path to CBOM JSON",
    )

    parser.add_argument(
        "--repo",
        required=True,
        help="Repository Name",
    )

    return parser.parse_args()
  # ==========================================================
# JSON Loader
# ==========================================================

def load_json(path: str):

    file = Path(path)

    if not file.exists():
        logger.error("File not found: %s", file)
        sys.exit(1)

    logger.info("Loading %s", file)

    try:

        with open(file, "r", encoding="utf-8") as f:

            return json.load(f)

    except json.JSONDecodeError as e:

        logger.exception("Invalid JSON")

        raise e
# ==========================================================
# Validation
# ==========================================================

def validate_sbom(sbom):

    logger.info("Validating SBOM...")

    if sbom.get("bomFormat") != "CycloneDX":
        raise ValueError("Invalid SBOM")

    logger.info("SBOM OK")


def validate_cbom(cbom):

    logger.info("Validating CBOM...")

    if cbom.get("bomFormat") != "CycloneDX":
        raise ValueError("Invalid CBOM")

    logger.info("CBOM OK")
# ==========================================================
# Claude Client
# ==========================================================

def get_claude_client():

    api_key = os.getenv(API_KEY_ENV)

    if not api_key:

        logger.error(
            "Environment variable %s not found",
            API_KEY_ENV,
        )

        sys.exit(1)

    logger.info("Claude API Key Found")

    return anthropic.Anthropic(
        api_key=api_key
    )
# ==========================================================
# Prompt Builder
# ==========================================================

def build_sbom_prompt(repo_name: str, sbom: dict) -> tuple[str, str]:
    """
    Returns:
        system_prompt, user_prompt
    """

    system_prompt = """
You are a Principal Software Supply Chain Security Architect,
Senior Open Source Compliance Officer,
Software Composition Analysis (SCA) Expert,
Enterprise Software Security Auditor,
and Open Source Legal Compliance Advisor.

You are generating an executive-level enterprise audit report.

Your audience includes:

• CTO
• CISO
• Security Architects
• DevSecOps Engineers
• Legal & Compliance Teams
• Software Developers

The report MUST be professional.

Never mention that you are an AI.

Never invent vulnerabilities.

Never invent licenses.

Never invent CVEs.

Only analyze the information contained in the supplied SBOM.

If information does not exist inside the SBOM,
explicitly state:

"Not present in supplied SBOM."

The report MUST be written in GitHub Markdown.

Use headings.

Use tables.

Use bullet lists.

Use risk indicators.

Use professional language.

The report MUST contain the following sections.

# Cover Page

Repository

Report Date

CycloneDX Version

Generated By

Report Classification

---

# Executive Summary

Provide a management summary.

---

# Project Metadata

Summarize

• project
• supplier
• author
• version
• components
• dependencies

---

# Dependency Inventory

Summarize

• direct dependencies

• transitive dependencies

• package ecosystems

• component statistics

---

# Component Analysis

Summarize important components.

---

# OSS License Inventory

Create a table

License

SPDX

Packages

Risk

---

# OSS License Compatibility Analysis

Analyze compatibility between detected licenses.

Identify

Compatible

Potential conflicts

Licenses requiring legal review

Explain WHY.

---

# OSS License Obligations

For EVERY detected license explain:

Attribution

Copyright

NOTICE

Source disclosure

Patent grants

Redistribution

Commercial use

Modification obligations

---

# Copyright & Attribution

Explain

Required notices

Missing notices

Copyright implications

---

# Security Analysis

Discuss

Supply chain risks

Unknown components

Deprecated components

Potential risks

Only use evidence from the SBOM.

---

# Compliance Mapping

Map findings against

SPDX

CycloneDX

OpenChain

ISO/IEC 5230

EU CRA

Explain applicability.

---

# Legal Risk Assessment

Discuss

Commercial distribution

Copyleft exposure

Unknown licenses

Enterprise risks

---

# Remediation Roadmap

Prioritize

Critical

High

Medium

Low

---

# Executive Conclusion

Provide a concise executive conclusion.

Finish with an Overall OSS Compliance Rating:

Excellent

Good

Needs Improvement

High Risk
"""

    user_prompt = f"""
Repository:

{repo_name}

Below is the SBOM in CycloneDX JSON.

Analyse it thoroughly.

SBOM:

{json.dumps(sbom, indent=2)}
"""

    return system_prompt, user_prompt

def build_cbom_prompt(repo_name: str, cbom: dict):

    system_prompt = """
You are a Principal Cryptography Security Architect,
NIST Cryptography Specialist,
FIPS 140-3 Compliance Auditor,
PCI DSS Security Assessor,
Post-Quantum Cryptography Advisor.

Generate an executive cryptographic audit report.

Never invent findings.

Only analyze evidence present in the supplied CBOM.

If information does not exist say:

"Not present in supplied CBOM."

Return GitHub Markdown.

Include tables.

Include headings.

Professional language.

The report MUST contain:

# Cover Page

# Executive Summary

# Cryptographic Asset Inventory

# Algorithm Inventory

# Weak Algorithms

# Deprecated Algorithms

# Key Material Analysis

# IV / Nonce Analysis

# Certificate Analysis

# Cryptographic Risk Assessment

# Compliance Mapping

Map to

NIST

FIPS 140-3

PCI DSS

OWASP

NSA CNSA

Explain each mapping.

# Post Quantum Readiness

Discuss migration readiness.

# Remediation Roadmap

Prioritize

Critical

High

Medium

Low

# Executive Conclusion

Provide an Overall Crypto Security Rating.

Excellent

Good

Needs Improvement

High Risk
"""

    user_prompt = f"""
Repository

{repo_name}

Below is the CBOM.

CBOM:

{json.dumps(cbom, indent=2)}
"""

    return system_prompt, user_prompt

# ==========================================================
# Claude API
# ==========================================================

def call_claude(client, system_prompt: str, user_prompt: str) -> str:
    """
    Send a prompt to Claude and return Markdown text.
    """

    logger.info("Sending request to Claude...")

    response = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=MAX_TOKENS,
        temperature=TEMPERATURE,
        system=system_prompt,
        messages=[
            {
                "role": "user",
                "content": user_prompt,
            }
        ],
    )

    logger.info("Claude response received.")

    return response.content[0].text
# ==========================================================
# Save Markdown
# ==========================================================

def save_markdown(path: str, content: str):

    output = Path(path)

    output.parent.mkdir(parents=True, exist_ok=True)

    with open(output, "w", encoding="utf-8") as f:
        f.write(content)

    logger.info("Saved report: %s", output)
def generate_sbom_report(client, repo_name, sbom):

    system_prompt, user_prompt = build_sbom_prompt(
        repo_name,
        sbom,
    )

    markdown = call_claude(
        client,
        system_prompt,
        user_prompt,
    )

    output = f"reports/SBOM/{repo_name}-report.md"

    save_markdown(output, markdown)

    return output
def generate_cbom_report(client, repo_name, cbom):

    system_prompt, user_prompt = build_cbom_prompt(
        repo_name,
        cbom,
    )

    markdown = call_claude(
        client,
        system_prompt,
        user_prompt,
    )

    output = f"reports/CBOM/{repo_name}-report.md"

    save_markdown(output, markdown)

    return output

# ==========================================================
# Output Directory
# ==========================================================

def create_output_directories():

    Path("reports/SBOM").mkdir(
        parents=True,
        exist_ok=True,
    )

    Path("reports/CBOM").mkdir(
        parents=True,
        exist_ok=True,
    )

    logger.info("Output directories ready")
# ==========================================================
# Main
# ==========================================================

def main():

    args = parse_arguments()

    logger.info("=" * 60)
    logger.info("Enterprise Report Generator")
    logger.info("=" * 60)

    create_output_directories()

    sbom = load_json(args.sbom)

    cbom = load_json(args.cbom)

    validate_sbom(sbom)

    validate_cbom(cbom)

    client = get_claude_client()

    logger.info("Repository : %s", args.repo)

    logger.info("SBOM Loaded")

    logger.info("CBOM Loaded")

    logger.info("Claude Connected")

    logger.info("Ready for Prompt Generation")


if __name__ == "__main__":

    main()
